/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const STORAGE_KEY = "galaxy-language";

const TRANSLATIONS = {
  en: {
    app_announcement: "Premium furniture • Custom orders • Fast delivery",
    app_city: "Addis Ababa",
    call: "Call",
    whatsapp: "WhatsApp",
    home: "Home",
    shop: "Shop",
    about: "About",
    contact: "Contact",
    open_menu: "Open menu",
    close_menu: "Close menu",
    menu: "Menu",
    brand_subtitle: "Premium Furniture | Addis Ababa",
    call_now: "Call Now",
    footer_tagline: "Gold & Navy quality furniture.",
    branches: "Branches",
    branch_suffix: "Branch",
    contact_title: "Contact",
    main: "Main",
    chat_with_us: "Chat with us",
    branch_phones: "phones",
    follow_us: "Follow us",
    rights: "All rights reserved. Built in Addis Ababa.",
    about_badge: "About Galaxy Furniture",
    about_heading: "Craftsmanship you can trust",
    about_body:
      "Galaxy Furniture is a furniture manufacturing and sales company with three branches and one central workshop. We focus on comfort, durability, and modern design.",
    owner: "Owner",
    phone: "Phone",
    workshop: "Workshop",
    vision: "Vision",
    vision_body: "To become the most trusted furniture brand in Ethiopia through quality and innovation.",
    mission: "Mission",
    mission_body: "To deliver beautiful, durable furniture with strong customer service and fair pricing.",
    contact_heading: "Let's talk about your furniture",
    contact_body: "Call us, visit our branches, or send a message. We respond fast.",
    whatsapp_message: "WhatsApp Message",
    social_media: "Social media",
    send_request: "Send a request",
    demo_form: "Demo form (front-end). If you want it to send email, tell me and I'll add it.",
    full_name: "Full Name",
    your_name: "Your name",
    phone_number: "Phone Number",
    what_do_you_need: "What do you need?",
    custom_order_placeholder: "Sofa / Bed / Custom order...",
    message: "Message",
    write_message: "Write your message...",
    submit_demo: "Submit (demo)",
    products: "Products",
    shop_by_category: "Shop by category",
    products_intro: "Filter items, open details, add to cart, then send your order on WhatsApp.",
    cart: "Cart",
    search_products: "Search products... (sofa, bed, wardrobe)",
    sort_featured: "Sort: Featured",
    sort_low_high: "Sort: Price (Low → High)",
    sort_high_low: "Sort: Price (High → Low)",
    sort_name: "Sort: Name (A → Z)",
    no_results: "No results",
    try_changing: "Try changing the category or search text.",
    items: "items",
    see_more_products: "See More Products",
    cart_summary: "Cart Summary",
    cart_demo: "Demo cart. You can send the order via WhatsApp or pay by bank transfer.",
    clear_cart: "Clear Cart",
    send_order_whatsapp: "Send Order on WhatsApp",
    cart_empty: "Your cart is empty. Add products to see them here.",
    total: "Total",
    bank_transfer_checkout: "Bank transfer checkout",
    send_receipt: "Send your receipt via WhatsApp after transfer.",
    bank_transfer: "Bank Transfer",
    request_price: "Request For The Price",
    colors: "Colors",
    add_to_cart: "Add to Cart",
    telegram: "Telegram",
    included_notes: "Included / Notes",
    custom_size_color: "Custom size & color available",
    delivery_ask_price: "Delivery available (ask for price)",
    high_quality_finishing: "High-quality materials & finishing",
    magnify: "Magnify",
    magnify_help: "Open magnify to inspect stitching, fabric texture, and finishing details.",
    zoom_help: "Zoom in to inspect finishing and stitching.",
    zoom_out: "Zoom Out",
    reset: "Reset",
    zoom_in: "Zoom In",
    close: "Close",
    product_detail: "Product Detail",
    esc_to_close: "ESC to close",
  },
  am: {
    app_announcement: "ዘመናዊ የቤት እቃዎች • በትዕዛዝ ማምረት • ፈጣን ዴሊቨሪ",
    app_city: "አዲስ አበባ",
    call: "ይደውሉ",
    whatsapp: "ዋትስአፕ",
    home: "መነሻ",
    shop: "ሱቅ",
    about: "ስለ እኛ",
    contact: "ያግኙን",
    open_menu: "ሜኑ ክፈት",
    close_menu: "ሜኑ ዝጋ",
    menu: "ሜኑ",
    brand_subtitle: "ዘመናዊ የቤት እቃዎች | አዲስ አበባ",
    call_now: "አሁን ይደውሉ",
    footer_tagline: "የወርቅ እና ኔቪ ጥራት ያለው ፈርኒቸር።",
    branches: "ቅርንጫፎች",
    branch_suffix: "ቅርንጫፍ",
    contact_title: "ያግኙን",
    main: "ዋና",
    chat_with_us: "ያውሩን",
    branch_phones: "ስልኮች",
    follow_us: "ይከተሉን",
    rights: "መብቶች በሙሉ የተጠበቁ ናቸው። በአዲስ አበባ የተሰራ።",
    about_badge: "ስለ ጋላክሲ ፈርኒቸር",
    about_heading: "ሊታመን የሚችል ሙያዊ ስራ",
    about_body:
      "ጋላክሲ ፈርኒቸር ሶስት ቅርንጫፎች እና አንድ ዋና ወርክሾፕ ያለው የቤት እቃ ምርትና ሽያጭ ድርጅት ነው። በምቾት፣ በጥንካሬ እና በዘመናዊ ዲዛይን ላይ እንተኩራለን።",
    owner: "ባለቤት",
    phone: "ስልክ",
    workshop: "ወርክሾፕ",
    vision: "ራዕይ",
    vision_body: "በጥራትና በፈጠራ ኢትዮጵያ ውስጥ እጅግ የሚታመን የቤት እቃ ብራንድ መሆን።",
    mission: "ተልዕኮ",
    mission_body: "ውብ፣ ጠንካራ እና በጥሩ ደንበኛ አገልግሎት የተደገፈ የቤት እቃ በተመጣጣኝ ዋጋ ማቅረብ።",
    contact_heading: "ስለ ፈርኒቸርዎ እንነጋገር",
    contact_body: "ይደውሉልን፣ ቅርንጫፎቻችንን ይጎብኙ ወይም መልዕክት ይላኩ። ፈጣን ምላሽ እንሰጣለን።",
    whatsapp_message: "በዋትስአፕ መልዕክት",
    social_media: "ማህበራዊ ሚዲያ",
    send_request: "ጥያቄ ይላኩ",
    demo_form: "ይህ የፊት ለፊት የሚታይ ፎርም ነው። ኢሜይል እንዲልክ ከፈለጉ እጨምርልዎታለሁ።",
    full_name: "ሙሉ ስም",
    your_name: "ስምዎ",
    phone_number: "ስልክ ቁጥር",
    what_do_you_need: "ምን ይፈልጋሉ?",
    custom_order_placeholder: "ሶፋ / አልጋ / በትዕዛዝ ስራ...",
    message: "መልዕክት",
    write_message: "መልዕክትዎን ይፃፉ...",
    submit_demo: "ላክ (ሙከራ)",
    products: "ምርቶች",
    shop_by_category: "በምድብ ይመልከቱ",
    products_intro: "ምርቶችን ይፈልጉ፣ ዝርዝር ይክፈቱ፣ ወደ ካርት ያክሉ እና በዋትስአፕ ይላኩ።",
    cart: "ካርት",
    search_products: "ምርቶችን ይፈልጉ... (ሶፋ፣ አልጋ፣ ዋርድሮብ)",
    sort_featured: "ለዩ ምርቶች",
    sort_low_high: "ዋጋ: ከዝቅተኛ ወደ ከፍተኛ",
    sort_high_low: "ዋጋ: ከከፍተኛ ወደ ዝቅተኛ",
    sort_name: "ስም: አ ወደ ፐ",
    no_results: "ምንም አልተገኘም",
    try_changing: "ምድቡን ወይም የፍለጋ ጽሑፉን ይቀይሩ።",
    items: "እቃዎች",
    see_more_products: "ተጨማሪ ምርቶች ይመልከቱ",
    cart_summary: "የካርት ማጠቃለያ",
    cart_demo: "ይህ ሙከራ ካርት ነው። ትዕዛዝዎን በዋትስአፕ መላክ ወይም በባንክ መክፈል ይችላሉ።",
    clear_cart: "ካርት አፅዳ",
    send_order_whatsapp: "ትዕዛዝን በዋትስአፕ ላክ",
    cart_empty: "ካርትዎ ባዶ ነው። ምርቶችን ያክሉ።",
    total: "ጠቅላላ",
    bank_transfer_checkout: "በባንክ ዝውውር ክፍያ",
    send_receipt: "ከክፍያ በኋላ ደረሰኙን በዋትስአፕ ይላኩ።",
    bank_transfer: "ባንክ ዝውውር",
    request_price: "ዋጋ ይጠይቁ",
    colors: "ቀለሞች",
    add_to_cart: "ወደ ካርት ጨምር",
    telegram: "ቴሌግራም",
    included_notes: "የተካተቱ / ማስታወሻዎች",
    custom_size_color: "በልክ እና በቀለም ማዘዝ ይቻላል",
    delivery_ask_price: "ዴሊቨሪ አለ (ዋጋ ይጠይቁ)",
    high_quality_finishing: "ከፍተኛ ጥራት ያለው ቁሳቁስ እና ፊኒሺንግ",
    magnify: "አሳድግ",
    magnify_help: "ስፌትን፣ የጨርቅ ጥራትን እና ፊኒሺንግን ለማየት ማጉላት ይክፈቱ።",
    zoom_help: "ፊኒሺንግን እና ስፌትን ለማየት ያጉሉ።",
    zoom_out: "አሳንስ",
    reset: "ዳግም አስጀምር",
    zoom_in: "አጉል",
    close: "ዝጋ",
    product_detail: "የምርት ዝርዝር",
    esc_to_close: "በ ESC ዝጋ",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || "en");

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "am" ? "am" : "en";
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
    const toggleLanguage = () => setLanguage((current) => (current === "en" ? "am" : "en"));
    return { language, setLanguage, toggleLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
